export type Cuisine = {
  cuisine_id: number;
  cuisine_name: string;
};

export const cuisines: Cuisine[] = [
  { cuisine_id: 6, cuisine_name: "Afghani" },
  { cuisine_id: 152, cuisine_name: "African" },
  { cuisine_id: 1, cuisine_name: "American" },
  { cuisine_id: 4, cuisine_name: "Arabian" },
  { cuisine_id: 151, cuisine_name: "Argentine" },
  { cuisine_id: 3, cuisine_name: "Asian" },
  { cuisine_id: 131, cuisine_name: "Australian" },
  { cuisine_id: 201, cuisine_name: "Austrian" },
  { cuisine_id: 193, cuisine_name: "BBQ" },
  { cuisine_id: 5, cuisine_name: "Bakery" },
  { cuisine_id: 145, cuisine_name: "Bangladeshi" },
  { cuisine_id: 227, cuisine_name: "Bar Food" },
  { cuisine_id: 132, cuisine_name: "Belgian" },
  { cuisine_id: 270, cuisine_name: "Beverages" },
  { cuisine_id: 195, cuisine_name: "Brasserie" },
  { cuisine_id: 159, cuisine_name: "Brazilian" },
  { cuisine_id: 182, cuisine_name: "Breakfast" },
  { cuisine_id: 133, cuisine_name: "British" },
  { cuisine_id: 247, cuisine_name: "Bubble Tea" },
  { cuisine_id: 168, cuisine_name: "Burger" },
  { cuisine_id: 22, cuisine_name: "Burmese" },
  { cuisine_id: 30, cuisine_name: "Cafe" },
  { cuisine_id: 111, cuisine_name: "Cambodian" },
  { cuisine_id: 121, cuisine_name: "Cantonese" },
  { cuisine_id: 158, cuisine_name: "Caribbean" },
  { cuisine_id: 994, cuisine_name: "Charcoal Chicken" },
  { cuisine_id: 25, cuisine_name: "Chinese" },
  { cuisine_id: 161, cuisine_name: "Coffee and Tea" },
  { cuisine_id: 287, cuisine_name: "Colombian" },
  { cuisine_id: 144, cuisine_name: "Contemporary" },
  { cuisine_id: 35, cuisine_name: "Continental" },
  { cuisine_id: 928, cuisine_name: "Creole" },
  { cuisine_id: 881, cuisine_name: "Crepes" },
  { cuisine_id: 982, cuisine_name: "Croatian" },
  { cuisine_id: 153, cuisine_name: "Cuban" },
  { cuisine_id: 192, cuisine_name: "Deli" },
  { cuisine_id: 100, cuisine_name: "Desserts" },
  { cuisine_id: 541, cuisine_name: "Diner" },
  { cuisine_id: 268, cuisine_name: "Drinks Only" },
  { cuisine_id: 985, cuisine_name: "Dumplings" },
  { cuisine_id: 204, cuisine_name: "Dutch" },
  { cuisine_id: 651, cuisine_name: "Eastern European" },
  { cuisine_id: 146, cuisine_name: "Egyptian" },
  { cuisine_id: 149, cuisine_name: "Ethiopian" },
  { cuisine_id: 38, cuisine_name: "European" },
  { cuisine_id: 571, cuisine_name: "Falafel" },
  { cuisine_id: 40, cuisine_name: "Fast Food" },
  { cuisine_id: 112, cuisine_name: "Filipino" },
  { cuisine_id: 271, cuisine_name: "Finger Food" },
  { cuisine_id: 298, cuisine_name: "Fish and Chips" },
  { cuisine_id: 45, cuisine_name: "French" },
  { cuisine_id: 501, cuisine_name: "Frozen Yogurt" },
  { cuisine_id: 274, cuisine_name: "Fusion" },
  { cuisine_id: 134, cuisine_name: "German" },
  { cuisine_id: 156, cuisine_name: "Greek" },
  { cuisine_id: 181, cuisine_name: "Grill" },
  { cuisine_id: 521, cuisine_name: "Hawaiian" },
  { cuisine_id: 143, cuisine_name: "Healthy Food" },
  { cuisine_id: 228, cuisine_name: "Hungarian" },
  { cuisine_id: 233, cuisine_name: "Ice Cream" },
  { cuisine_id: 148, cuisine_name: "Indian" },
  { cuisine_id: 114, cuisine_name: "Indonesian" },
  { cuisine_id: 154, cuisine_name: "International" },
  { cuisine_id: 206, cuisine_name: "Iraqi" },
  { cuisine_id: 135, cuisine_name: "Irish" },
  { cuisine_id: 218, cuisine_name: "Israeli" },
  { cuisine_id: 55, cuisine_name: "Italian" },
  { cuisine_id: 60, cuisine_name: "Japanese" },
  { cuisine_id: 164, cuisine_name: "Juices" },
  { cuisine_id: 178, cuisine_name: "Kebab" },
  { cuisine_id: 891, cuisine_name: "Kebabs" },
  { cuisine_id: 67, cuisine_name: "Korean" },
  { cuisine_id: 136, cuisine_name: "Latin American" },
  { cuisine_id: 66, cuisine_name: "Lebanese" },
  { cuisine_id: 69, cuisine_name: "Malaysian" },
  { cuisine_id: 977, cuisine_name: "Meat Pie" },
  { cuisine_id: 70, cuisine_name: "Mediterranean" },
  { cuisine_id: 73, cuisine_name: "Mexican" },
  { cuisine_id: 137, cuisine_name: "Middle Eastern" },
  { cuisine_id: 969, cuisine_name: "Modern Australian" },
  { cuisine_id: 294, cuisine_name: "Modern European" },
  { cuisine_id: 147, cuisine_name: "Moroccan" },
  { cuisine_id: 117, cuisine_name: "Nepalese" },
  { cuisine_id: 278, cuisine_name: "Oriental" },
  { cuisine_id: 110, cuisine_name: "Others" },
  { cuisine_id: 139, cuisine_name: "Pakistani" },
  { cuisine_id: 209, cuisine_name: "Pan Asian" },
  { cuisine_id: 306, cuisine_name: "Pastry" },
  { cuisine_id: 183, cuisine_name: "Patisserie" },
  { cuisine_id: 81, cuisine_name: "Persian" },
  { cuisine_id: 162, cuisine_name: "Peruvian" },
  { cuisine_id: 82, cuisine_name: "Pizza" },
  { cuisine_id: 219, cuisine_name: "Polish" },
  { cuisine_id: 87, cuisine_name: "Portuguese" },
  { cuisine_id: 983, cuisine_name: "Pub Food" },
  { cuisine_id: 320, cuisine_name: "Ramen" },
  { cuisine_id: 84, cuisine_name: "Russian" },
  { cuisine_id: 304, cuisine_name: "Sandwich" },
  { cuisine_id: 312, cuisine_name: "Satay" },
  { cuisine_id: 691, cuisine_name: "Scandinavian" },
  { cuisine_id: 210, cuisine_name: "Scottish" },
  { cuisine_id: 83, cuisine_name: "Seafood" },
  { cuisine_id: 831, cuisine_name: "Shanghai" },
  { cuisine_id: 128, cuisine_name: "Sichuan" },
  { cuisine_id: 119, cuisine_name: "Singaporean" },
  { cuisine_id: 461, cuisine_name: "Soul Food" },
  { cuisine_id: 267, cuisine_name: "South African" },
  { cuisine_id: 89, cuisine_name: "Spanish" },
  { cuisine_id: 86, cuisine_name: "Sri Lankan" },
  { cuisine_id: 141, cuisine_name: "Steak" },
  { cuisine_id: 90, cuisine_name: "Street Food" },
  { cuisine_id: 177, cuisine_name: "Sushi" },
  { cuisine_id: 211, cuisine_name: "Swedish" },
  { cuisine_id: 212, cuisine_name: "Syrian" },
  { cuisine_id: 190, cuisine_name: "Taiwanese" },
  { cuisine_id: 179, cuisine_name: "Tapas" },
  { cuisine_id: 163, cuisine_name: "Tea" },
  { cuisine_id: 481, cuisine_name: "Tea House" },
  { cuisine_id: 981, cuisine_name: "Teppanyaki" },
  { cuisine_id: 964, cuisine_name: "Teriyaki" },
  { cuisine_id: 150, cuisine_name: "Tex-Mex" },
  { cuisine_id: 95, cuisine_name: "Thai" },
  { cuisine_id: 93, cuisine_name: "Tibetan" },
  { cuisine_id: 142, cuisine_name: "Turkish" },
  { cuisine_id: 186, cuisine_name: "Turkish Pizza" },
  { cuisine_id: 308, cuisine_name: "Vegetarian" },
  { cuisine_id: 99, cuisine_name: "Vietnamese" },
  { cuisine_id: 978, cuisine_name: "Yum Cha" },
];
