export type CategoryResponse = {
  categories: Category[];
};

export type Category = {
  alias: string;
  title: string;
  parent_aliases?: string[];
  country_whitelist?: string[];
  country_blacklist?: string[];
};

// TODO: Temporary hack until we find a better way of handling CORS
export const categories: Category[] = [
  {
    alias: "acaibowls",
    title: "Acai Bowls",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["AR", "CL", "IT", "MX", "PL", "TR"],
  },
  {
    alias: "afghani",
    title: "Afghan",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["MX", "TR"],
  },
  {
    alias: "african",
    title: "African",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["TR"],
  },
  {
    alias: "arabian",
    title: "Arabic",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["DK"],
  },
  {
    alias: "argentine",
    title: "Argentine",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["FI"],
  },
  {
    alias: "asianfusion",
    title: "Asian Fusion",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "australian",
    title: "Australian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "austrian",
    title: "Austrian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["DK", "ES"],
  },
  {
    alias: "bagels",
    title: "Bagels",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["AU", "ES"],
  },
  {
    alias: "bakeries",
    title: "Bakeries",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "bangladeshi",
    title: "Bangladeshi",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["DK", "ES", "MX", "PT", "TR"],
  },
  {
    alias: "basque",
    title: "Basque",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["AU", "CZ", "DK", "PT", "SG", "TR"],
  },
  {
    alias: "beer_and_wine",
    title: "Beer, Wine & Spirits",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "belgian",
    title: "Belgian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "beverage_stores",
    title: "Beverage Store",
    parent_aliases: ["food"],
    country_whitelist: [
      "AT",
      "AU",
      "BE",
      "CH",
      "CL",
      "DE",
      "ES",
      "IT",
      "NL",
      "PT",
      "TR",
      "US",
    ],
    country_blacklist: [],
  },
  {
    alias: "bistros",
    title: "Bistros",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["US"],
  },
  {
    alias: "brasseries",
    title: "Brasseries",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["AR", "MX"],
  },
  {
    alias: "brazilian",
    title: "Brazilian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "breakfast_brunch",
    title: "Breakfast & Brunch",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "breweries",
    title: "Breweries",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "british",
    title: "British",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["FI"],
  },
  {
    alias: "bubbletea",
    title: "Bubble Tea",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["AR", "AT", "CH", "ES", "MX", "TR"],
  },
  {
    alias: "buffets",
    title: "Buffets",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "bulgarian",
    title: "Bulgarian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["BR", "CA", "DK", "NL", "NO", "NZ", "SG", "TR"],
  },
  {
    alias: "burgers",
    title: "Burgers",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "burmese",
    title: "Burmese",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["CZ", "DK", "ES", "FI", "PT", "TR"],
  },
  {
    alias: "butcher",
    title: "Butcher",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["AT", "CH", "DE"],
  },
  {
    alias: "cafes",
    title: "Cafes",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["AR", "ES", "FI", "MX"],
  },
  {
    alias: "cafeteria",
    title: "Cafeteria",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["BR", "CA", "FR", "IE", "NZ", "SE", "SG"],
  },
  {
    alias: "cajun",
    title: "Cajun/Creole",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["AU", "ES", "PT", "SG"],
  },
  {
    alias: "cakeshop",
    title: "Patisserie/Cake Shop",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "cambodian",
    title: "Cambodian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["CZ", "DK", "ES", "FI", "PT", "TR"],
  },
  {
    alias: "caribbean",
    title: "Caribbean",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["FI", "PT", "TR"],
  },
  {
    alias: "chech",
    title: "Chech",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "cheesesteaks",
    title: "Cheesesteaks",
    parent_aliases: ["restaurants"],
    country_whitelist: ["AU", "CA", "GB", "IE", "NL", "PL", "US"],
    country_blacklist: [],
  },
  {
    alias: "chicken_wings",
    title: "Chicken Wings",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [
      "BE",
      "CH",
      "CL",
      "DK",
      "ES",
      "FI",
      "FR",
      "IT",
      "JP",
      "NL",
      "NO",
      "PT",
    ],
  },
  {
    alias: "chickenshop",
    title: "Chicken Shop",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["CZ"],
  },
  {
    alias: "chinese",
    title: "Chinese",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "cideries",
    title: "Cideries",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["BE", "DK", "FR", "IT", "JP", "NL", "NO", "TR"],
  },
  {
    alias: "coffee",
    title: "Coffee & Tea",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "coffeeroasteries",
    title: "Coffee Roasteries",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "coffeeteasupplies",
    title: "Coffee & Tea Supplies",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [
      "AR",
      "BR",
      "CL",
      "CZ",
      "ES",
      "FI",
      "IT",
      "MX",
      "MY",
      "PH",
      "PT",
      "US",
    ],
  },
  {
    alias: "convenience",
    title: "Convenience Stores",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["FI"],
  },
  {
    alias: "creperies",
    title: "Creperies",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "cuban",
    title: "Cuban",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["DK", "SG", "TR"],
  },
  {
    alias: "cupcakes",
    title: "Cupcakes",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["CA", "CZ", "ES", "TR"],
  },
  {
    alias: "customcakes",
    title: "Custom Cakes",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["AT", "CH", "DE", "FR"],
  },
  {
    alias: "czech",
    title: "Czech",
    parent_aliases: ["restaurants"],
    country_whitelist: [
      "AU",
      "BE",
      "CA",
      "CZ",
      "DE",
      "DK",
      "FI",
      "FR",
      "GB",
      "IE",
      "IT",
      "NO",
      "PL",
      "SE",
      "US",
    ],
    country_blacklist: [],
  },
  {
    alias: "delicatessen",
    title: "Delicatessen",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["US"],
  },
  {
    alias: "delis",
    title: "Delis",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["BE", "CL", "FR", "IT", "NL", "PT", "SE"],
  },
  {
    alias: "desserts",
    title: "Desserts",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "dinnertheater",
    title: "Dinner Theater",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["BE", "FR", "IT", "JP", "NL"],
  },
  {
    alias: "distilleries",
    title: "Distilleries",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "diyfood",
    title: "Do-It-Yourself Food",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [
      "AT",
      "CH",
      "CL",
      "CZ",
      "DE",
      "ES",
      "FI",
      "FR",
      "IT",
      "MX",
      "NZ",
      "SE",
    ],
  },
  {
    alias: "donuts",
    title: "Donuts",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["ES"],
  },
  {
    alias: "dumplings",
    title: "Dumplings",
    parent_aliases: ["restaurants"],
    country_whitelist: [
      "JP",
      "BE",
      "CH",
      "NL",
      "SG",
      "CA",
      "DE",
      "NZ",
      "AU",
      "GB",
      "IE",
      "PL",
      "AT",
    ],
    country_blacklist: [],
  },
  {
    alias: "eastern_european",
    title: "Eastern European",
    parent_aliases: ["restaurants"],
    country_whitelist: ["AU", "CZ", "DK", "FR", "NO"],
    country_blacklist: [],
  },
  {
    alias: "ethiopian",
    title: "Ethiopian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["CZ", "MX", "SG", "TR"],
  },
  {
    alias: "ethnicgrocery",
    title: "Ethnic Grocery",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "farmersmarket",
    title: "Farmers Market",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "filipino",
    title: "Filipino",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["CZ", "DK", "FI", "TR"],
  },
  {
    alias: "fischbroetchen",
    title: "Fischbroetchen",
    parent_aliases: ["restaurants"],
    country_whitelist: ["DE"],
    country_blacklist: [],
  },
  {
    alias: "fishmonger",
    title: "Fishmonger",
    parent_aliases: ["food"],
    country_whitelist: [
      "AT",
      "AU",
      "BE",
      "CZ",
      "DE",
      "DK",
      "FI",
      "IT",
      "NL",
      "NO",
      "PL",
      "PT",
      "SE",
      "CH",
    ],
    country_blacklist: [],
  },
  {
    alias: "fishnchips",
    title: "Fish & Chips",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["BR", "PT"],
  },
  {
    alias: "fondue",
    title: "Fondue",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["CZ", "DK", "ES"],
  },
  {
    alias: "food_court",
    title: "Food Court",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["FI", "FR", "TR", "TW"],
  },
  {
    alias: "fooddeliveryservices",
    title: "Food Delivery Services",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "foodstands",
    title: "Food Stands",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "foodtrucks",
    title: "Food Trucks",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["SG"],
  },
  {
    alias: "french",
    title: "French",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "friterie",
    title: "Friterie",
    parent_aliases: ["food"],
    country_whitelist: ["AU", "BE", "FR", "IT", "NL", "PL"],
    country_blacklist: [],
  },
  {
    alias: "gamemeat",
    title: "Game Meat",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [
      "AR",
      "BR",
      "CA",
      "CL",
      "FI",
      "HK",
      "JP",
      "MX",
      "MY",
      "PH",
      "PT",
      "TR",
      "TW",
    ],
  },
  {
    alias: "gastropubs",
    title: "Gastropubs",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "gelato",
    title: "Gelato",
    parent_aliases: ["food"],
    country_whitelist: [
      "AU",
      "CZ",
      "DK",
      "IT",
      "NO",
      "PH",
      "PL",
      "PT",
      "SE",
      "SG",
      "US",
    ],
    country_blacklist: [],
  },
  {
    alias: "german",
    title: "German",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "giblets",
    title: "Giblets",
    parent_aliases: ["restaurants"],
    country_whitelist: ["TR"],
    country_blacklist: [],
  },
  {
    alias: "gluten_free",
    title: "Gluten-Free",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "gourmet",
    title: "Specialty Food",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "greek",
    title: "Greek",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "grocery",
    title: "Grocery",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "guamanian",
    title: "Guamanian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["AR", "CL", "FR", "JP", "MX", "PL", "TR"],
  },
  {
    alias: "halal",
    title: "Halal",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["PT", "TR"],
  },
  {
    alias: "himalayan",
    title: "Himalayan/Nepalese",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "honduran",
    title: "Honduran",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["JP", "TR"],
  },
  {
    alias: "hotdog",
    title: "Hot Dogs",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "hotdogs",
    title: "Fast Food",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "hungarian",
    title: "Hungarian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "icecream",
    title: "Ice Cream & Frozen Yogurt",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "importedfood",
    title: "Imported Food",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "indonesian",
    title: "Indonesian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["ES", "MX"],
  },
  {
    alias: "indpak",
    title: "Indian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "international",
    title: "International",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["FI", "IT", "MY", "PH", "TR", "US"],
  },
  {
    alias: "internetcafe",
    title: "Internet Cafes",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "intlgrocery",
    title: "International Grocery",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "irish",
    title: "Irish",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "italian",
    title: "Italian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "japanese",
    title: "Japanese",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "juicebars",
    title: "Juice Bars & Smoothies",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "kebab",
    title: "Kebab",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "kiosk",
    title: "Kiosk",
    parent_aliases: ["food", "shopping"],
    country_whitelist: [],
    country_blacklist: [
      "BR",
      "CA",
      "FR",
      "GB",
      "HK",
      "IE",
      "IT",
      "NZ",
      "SG",
      "US",
    ],
  },
  {
    alias: "korean",
    title: "Korean",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "kosher",
    title: "Kosher",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["PT", "TR"],
  },
  {
    alias: "laos",
    title: "Laos",
    parent_aliases: ["restaurants"],
    country_whitelist: ["AU"],
    country_blacklist: [],
  },
  {
    alias: "laotian",
    title: "Laotian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["CZ"],
  },
  {
    alias: "latin",
    title: "Latin American",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "malaysian",
    title: "Malaysian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["CZ", "ES", "PT", "TR"],
  },
  {
    alias: "mediterranean",
    title: "Mediterranean",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "mexican",
    title: "Mexican",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "mideastern",
    title: "Middle Eastern",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["BR"],
  },
  {
    alias: "milkbars",
    title: "Milk Bars",
    parent_aliases: ["restaurants"],
    country_whitelist: ["AU", "PL"],
    country_blacklist: [],
  },
  {
    alias: "modern_australian",
    title: "Modern Australian",
    parent_aliases: ["restaurants"],
    country_whitelist: ["AU"],
    country_blacklist: [],
  },
  {
    alias: "modern_european",
    title: "Modern European",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "mongolian",
    title: "Mongolian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["ES", "FI", "PT", "TR"],
  },
  {
    alias: "moroccan",
    title: "Moroccan",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["TR"],
  },
  {
    alias: "nicaraguan",
    title: "Nicaraguan",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["AR", "CL"],
  },
  {
    alias: "noodles",
    title: "Noodles",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["AT", "CH", "DE", "FR"],
  },
  {
    alias: "organic_stores",
    title: "Organic Stores",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "pakistani",
    title: "Pakistani",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "panasian",
    title: "Pan Asian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["IT"],
  },
  {
    alias: "parma",
    title: "Parma",
    parent_aliases: ["restaurants"],
    country_whitelist: ["AU"],
    country_blacklist: [],
  },
  {
    alias: "persian",
    title: "Persian/Iranian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "peruvian",
    title: "Peruvian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["PT", "SG", "TR"],
  },
  {
    alias: "pita",
    title: "Pita",
    parent_aliases: ["restaurants"],
    country_whitelist: ["TR"],
    country_blacklist: [],
  },
  {
    alias: "pizza",
    title: "Pizza",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "poke",
    title: "Poke",
    parent_aliases: ["food"],
    country_whitelist: [
      "BE",
      "CA",
      "FR",
      "NL",
      "SE",
      "US",
      "CH",
      "SG",
      "DE",
      "NZ",
      "AU",
      "GB",
      "IE",
      "AT",
    ],
    country_blacklist: [],
  },
  {
    alias: "polish",
    title: "Polish",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["FI", "SG"],
  },
  {
    alias: "popuprestaurants",
    title: "Pop-Up Restaurants",
    parent_aliases: ["restaurants"],
    country_whitelist: [
      "BE",
      "FR",
      "NL",
      "DK",
      "NO",
      "MY",
      "CA",
      "DE",
      "US",
      "HK",
      "NZ",
      "AU",
      "GB",
      "TW",
      "SG",
      "PH",
      "IE",
      "SE",
    ],
    country_blacklist: [],
  },
  {
    alias: "portuguese",
    title: "Portuguese",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["FI"],
  },
  {
    alias: "potatoes",
    title: "Potatoes",
    parent_aliases: ["restaurants"],
    country_whitelist: ["AT", "AU", "CH", "DE"],
    country_blacklist: [],
  },
  {
    alias: "pubfood",
    title: "Pub Food",
    parent_aliases: ["restaurants"],
    country_whitelist: ["AU"],
    country_blacklist: [],
  },
  {
    alias: "raw_food",
    title: "Live/Raw Food",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "rotisserie_chicken",
    title: "Rotisserie Chicken",
    parent_aliases: ["restaurants"],
    country_whitelist: [
      "AR",
      "AU",
      "BE",
      "BR",
      "CL",
      "ES",
      "FR",
      "IT",
      "MX",
      "NL",
      "NZ",
      "PL",
      "PT",
    ],
    country_blacklist: [],
  },
  {
    alias: "rumanian",
    title: "Rumanian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "russian",
    title: "Russian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "salad",
    title: "Salad",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "sandwiches",
    title: "Sandwiches",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "scandinavian",
    title: "Scandinavian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["PT"],
  },
  {
    alias: "seafood",
    title: "Seafood",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "singaporean",
    title: "Singaporean",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["CZ", "DK", "ES", "FI", "PT", "TR"],
  },
  {
    alias: "slovakian",
    title: "Slovakian",
    parent_aliases: ["restaurants"],
    country_whitelist: [
      "AU",
      "BE",
      "CA",
      "CZ",
      "FR",
      "GB",
      "IE",
      "IT",
      "PL",
      "US",
    ],
    country_blacklist: [],
  },
  {
    alias: "smokehouse",
    title: "Smokehouse",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: ["AR", "CL", "FR", "IT", "MX", "PL", "TR"],
  },
  {
    alias: "soup",
    title: "Soup",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "spanish",
    title: "Spanish",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "srilankan",
    title: "Sri Lankan",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["CZ"],
  },
  {
    alias: "steak",
    title: "Steakhouses",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "streetvendors",
    title: "Street Vendors",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "sushi",
    title: "Sushi Bars",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "syrian",
    title: "Syrian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "tabernas",
    title: "Tabernas",
    parent_aliases: ["restaurants"],
    country_whitelist: ["ES", "PT", "TR"],
    country_blacklist: [],
  },
  {
    alias: "taiwanese",
    title: "Taiwanese",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["CZ", "ES", "FI", "PT", "TR"],
  },
  {
    alias: "tapasmallplates",
    title: "Tapas/Small Plates",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "tea",
    title: "Tea Rooms",
    parent_aliases: ["food"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "thai",
    title: "Thai",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "tradamerican",
    title: "American (Traditional)",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "turkish",
    title: "Turkish",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "ukrainian",
    title: "Ukrainian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: ["DK", "ES", "TR"],
  },
  {
    alias: "vegan",
    title: "Vegan",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "vegetarian",
    title: "Vegetarian",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "venison",
    title: "Venison",
    parent_aliases: ["restaurants"],
    country_whitelist: [
      "AU",
      "CA",
      "CZ",
      "DK",
      "GB",
      "IE",
      "IT",
      "NO",
      "NZ",
      "PL",
      "SG",
    ],
    country_blacklist: [],
  },
  {
    alias: "vietnamese",
    title: "Vietnamese",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "waffles",
    title: "Waffles",
    parent_aliases: ["restaurants"],
    country_whitelist: [],
    country_blacklist: [],
  },
  {
    alias: "wineries",
    title: "Wineries",
    parent_aliases: ["arts", "food"],
    country_whitelist: [],
    country_blacklist: ["FI"],
  },
  {
    alias: "yugoslav",
    title: "Yugoslav",
    parent_aliases: ["restaurants"],
    country_whitelist: ["AU", "BE", "FR", "IT", "PT", "SE"],
    country_blacklist: [],
  },
];
